#**NumPy Nedir?**

In [ ]:
# NumPy açık kaynaklı kodlu ücretsiz ve özgür bir Python kütüphanesidir.
# NumPy --> Numerical Python anlamına gelir. Sayılarla daha hızlı matematik işlemler yapmamızı sağlar
# NumPy kütüphanesinin en temel elemanı array(dizi)'dir.
# Arrayler Listelerden yaklaşık 50 kat daha hızlı çalışır.
# NumPy arraylerinin hızlı çalışmasının sebebi bu kütüphanenin çok büyük oranda C ve C++ ile yazılmış olması.

#**NumPy Yüklenmesi**

In [ ]:
!pip install numpy

#**NumPy'ı projeye dahil etme**

In [ ]:
import numpy as np

#**NumPy Arrayleri Oluşturma**

In [ ]:
# Arrayler çok boyutlu diziler gibi düşünebilir.
# Arraylerin boyutları(dimension) vardır. 0d , 1d , 2d ,3d ,4d ....

# Arrayleri oluşturmanın 3 farklı yolu vardır.
# 1) Liste ya da tuple benzeri nesneleri array'e döndürebiliriz.                 np.array([1,2,3])
# 2) Built-in hazır fonksiyonlar yardımıyla arrayler oluşturabiliriz.            np.arange() , np.linspace() , np.logspace() vb.
# 3) Rastgele data üreterek                                                      np.random modülünün içindeki fonksiyonlar yardımıyla.


In [ ]:
# Boyutu açıklamak için küp şeklini kullan
# 1d = kenar, 2d = küpün 1 yüzü, 3d = yüzeylerin birleşerek yüzeyi oluşturması

In [ ]:
arr0d = np.array(42)
arr0d

array(42)

In [ ]:
arr1d = np.array([12,22,25,32])
arr1d

array([12, 22, 25, 32])

In [ ]:
arr2d = np.array([[10,20,30],
                  [50,60,70]])
arr2d

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
arr3d = np.array([[[10,20,30],
                   [40,50,60]],
                  [[70,80,90],
                   [100,110,120]]])
arr3d

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

#**Built-in Functionlarla Hızlıca NumPy Arrayleri Oluşturma**

In [ ]:
# np.arange() fonksiyonu ile hızlıca arrayler oluşturabiliriz. İstediğimiz sayı aralığında ardışık artan arrayler oluştururuz.
# Kullanımı aynen range() gibi. Start point dahil, End point dahil değil.
# Gene aynı range() fonksiyonunda olduğu gibi (start-stop-step parametrelerini alır.)

In [ ]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(50,100,3)

array([50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [ ]:
np.linspace(30,50,6 , dtype=int) # Endpoint bunda dahil.

array([30, 34, 38, 42, 46, 50])

In [ ]:
np.logspace(1,3 , 5) # 10**1 ile 10**3 arasında logaritmik artış yapan 5 tane veriden oluşan bir array oluştur.

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
np.zeros(5 , dtype= 'int')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3) , dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(10 , dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((3,5) , dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((2,3,5) , dtype = int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
np.eye(5 , dtype = 'int') # 5x5 birim matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.random.rand(3) # 3 tane 0-1 aralığında değerden oluşan bir array oluşturur.

array([0.39041431, 0.76975972, 0.63876584])

In [ ]:
np.random.rand(2,5)

array([[0.25712929, 0.16753203, 0.84715231, 0.69746211, 0.04971627],
       [0.8685232 , 0.2246312 , 0.55086156, 0.5554334 , 0.55119842]])

In [ ]:
np.random.rand(3) * 10 # 3 tane 0-10 aralığında değerden oluşan bir array oluşturdu.

array([7.34689361, 8.02242058, 7.67731973])

In [ ]:
np.random.randint(15,50,5)

array([25, 37, 39, 24, 25])

In [ ]:
np.random.randint(0,100, (3,6))

array([[ 3, 36, 99, 62, 11, 83],
       [46, 52, 88, 84, 37, 88],
       [ 9, 62, 53, 13, 80, 79]])

#**Arrayin Boyut Sayısını ve Shape'ini Kontrol Etmek**

In [ ]:
arr0d

array(42)

In [ ]:
arr1d

array([12, 22, 25, 32])

In [ ]:
arr2d

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
arr3d

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
arr0d.ndim

0

In [ ]:
arr1d.ndim

1

In [ ]:
arr2d.ndim

2

In [ ]:
arr3d.ndim

3

In [ ]:
# .shape attribute'ı ile arrayin shapeine bakılabilir

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr3d.shape

(2, 2, 3)

#**NumPy Arraylerini İndeksleme ve Öğelerime Erişme**

In [ ]:
arr1d # 1 boyutlu arrayler aynı listeler gibi düşünülebilir.

array([12, 22, 25, 32])

In [ ]:
arr1d[3]

32

In [ ]:
arr2d

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
arr2d[0]

array([10, 20, 30])

In [ ]:
arr2d[0][2] # arr2d[3,2]

30

In [ ]:
arr3d

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
arr3d[0]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr3d[0][0]

array([10, 20, 30])

In [ ]:
arr3d[0][0][2] # arr3d[0,0,2]

30

#**NumPy Dizilerinin Maximum-Minimum Elemanlarına ve bu Elemanların İndexlerine Erişme**

In [ ]:
arr = np.random.randint(1,100,10)
arr

array([71,  7, 86, 90, 80, 60, 19,  8, 89, 56])

In [ ]:
arr.max()

90

In [ ]:
arr.argmax()

3

In [ ]:
arr.min()

7

In [ ]:
arr.argmin()

1

#**NumPy Arraylerinde Slicing(Dilimleme) Yapılabilir**

In [ ]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
arr[0:6]

array([50, 51, 52, 53, 54, 55])

In [ ]:
arr[-5:]

array([60, 61, 62, 63, 64])

In [ ]:
arr[-5:-2]

array([60, 61, 62])

In [ ]:
arr[0:6] = 999 # Broadcasting

In [ ]:
arr

array([999, 999, 999, 999, 999, 999,  56,  57,  58,  59,  60,  61,  62,
        63,  64])

#**Bir Arrayin Veri Türünü(Data Type'ını) Kontrol Etme**

In [ ]:
# .dtype attribute'ı ile arrayimizin data type'ı kontrol edilebilir.

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.arange(100, dtype = 'float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
arr3.dtype # Unicode karakter dizinde en fazla 1 karakter olan

dtype('<U1')

#**Bir Arrayin Dtype'ını Değiştirme**

In [ ]:
arr = np.array([1.2 , 3.5 , 5.8])
arr

array([1.2, 3.5, 5.8])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
# .astype() methodu ile arraylerin dtype'ı değiştirebilir.

In [ ]:
arr.astype("int") #arr.astype(int)

array([1, 3, 5])

In [ ]:
arr.astype(str)

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

#**Bir Array'i Reshape(Yeniden Şekillendirme) Etme**

In [ ]:
# .reshape() metodu arrayin şeklini değiştirmeye yarar.
# .reshape() yaparken toplam eleman sayısını sabit tutmaya dikkat edilmeli.

In [ ]:
arr3d

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
arr3d.shape # 12

(2, 2, 3)

In [ ]:
arr2d = arr3d.reshape(2,6)
arr2d

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [ ]:
arr2d = arr3d.reshape(4,3)
arr2d

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr3d = np.arange(30).reshape(3,2,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
# Bilinmeyet Boyut !
# .reshape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine -1 yazıp otomatik hesaplattırabiliriz.

In [ ]:
arr3d = np.arange(120).reshape(5,2,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

#**Arrayleri Düzleştirme(Flatten)**



In [ ]:
# Düzleştirme işlemi(Flatten) çok boyutlu bir array'i 1 boyutlu hale döndürmeye denir.
# Basitçe .reshape(-1) metoduyla yapılır.

In [ ]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr2d.shape

(8, 5)

In [ ]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [ ]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

#**Çok Boyutlu Arraylerde Iteration(Yineleme)**

In [ ]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for x in arr1d:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for x in arr2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for x in arr2d:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for x in arr3d:
  for y in x:
    for z in y:
      print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


#**Çok Boyutlu Arraylerde nditer() Kullanımı**

In [ ]:
# For döngüsü arrayin boyutu kadar sayıda kullanılırsa ancak array'in bütün elemanlarına tek tek erişebiliriz.
# Çok boyutlu arraylerde nditer() fonksiyonu bunun için geliştirilmiştir.
# For döngüsüne çok daha efektif ve hızlı bir şekilde tüm elemanları dönmenizi sağlar.

In [ ]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


#**Array Elemanları Arasında 4 İşlem**

In [ ]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,4])

In [ ]:
arr1

array([ 10,  20,  50, 100])

In [ ]:
arr2

array([5, 7, 9, 4])

In [ ]:
arr1 + arr2

array([ 15,  27,  59, 104])

In [ ]:
arr1 - arr2

array([ 5, 13, 41, 96])

In [ ]:
arr1 * arr2

array([ 50, 140, 450, 400])

In [ ]:
arr1 ** arr2

array([          100000,       1280000000, 1953125000000000,
              100000000])

In [ ]:
arr1 / arr2

array([ 2.        ,  2.85714286,  5.55555556, 25.        ])

In [ ]:
arr1 // arr2

array([ 2,  2,  5, 25])

#**Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma**

In [ ]:
# Varyans ve standart sapma, bir veri setinin dağılma derecesini ölçen istatistiksel kavramlardır.
# Bu iki ölçü, verilerin ortalamadan ne kadar uzaklaştığını anlamamıza yardımcı olur.
# Varyans, daha geniş bir dağılma ölçüsü sunarken, standart sapma daha anlaşılır bir ölçüdür.

In [ ]:
arr = np.random.randint(0,10, 10)
arr

array([7, 8, 0, 3, 6, 9, 1, 7, 7, 9])

In [ ]:
arr.sum()

57

In [ ]:
arr.mean()

5.7

In [ ]:
arr.var()

9.41

In [ ]:
arr.std()

3.0675723300355937

In [ ]:
arr

array([7, 8, 0, 3, 6, 9, 1, 7, 7, 9])

In [ ]:
np.sqrt(arr)

array([2.64575131, 2.82842712, 0.        , 1.73205081, 2.44948974,
       3.        , 1.        , 2.64575131, 2.64575131, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.6569866 ,  0.98935825,  0.        ,  0.14112001, -0.2794155 ,
        0.41211849,  0.84147098,  0.6569866 ,  0.6569866 ,  0.41211849])

#**NumPy Arraylerini Birleştirme (Concatenate)**

In [ ]:
# Numpy Arraylerini birleştirme işlemi .concatenate() fonksiyonu ile yapılır. Fonksiyonun içine liste halinde birleştirilecek arrayler verilir.
# np.concatenate([arr1,arr2] , axis = 1)

In [ ]:
arr1 = np.array([10,20,30,70])
arr2 = np.array([100,200,600,900])

In [ ]:
arr1

array([10, 20, 30, 70])

In [ ]:
arr2

array([100, 200, 600, 900])

In [ ]:
np.concatenate([arr1, arr2], axis=0)

array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [ ]:
np.concatenate([arr1, arr2], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arr1 = np.array([[1,2,3] , [5,6,7]])
arr2 = np.array([[100,200,300] , [700,800,900]])

In [ ]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [ ]:
np.concatenate([arr1, arr2], axis=0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [ ]:
np.concatenate([arr1, arr2], axis=1)

array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7, 700, 800, 900]])

#**NumPy Arraylerinde Arama**

In [ ]:
# Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonksiyonunu kullanarız.
# np.where() içerisine argüman olarak condition(şart) alır.

In [ ]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [ ]:
np.where(arr == 9) # Arrayimizin kaçıncı indeksindeki elemanlar 9'dur ?

(array([6]),)

In [ ]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [ ]:
np.where(arr%2 != 0 ) # Tek elemanların indeksleri

(array([0, 2, 4, 5, 6]),)

In [ ]:
np.where(arr > 3 )

(array([2, 3, 4, 5, 6]),)

#**NumPy'da Random Kütüphanesi**

In [ ]:
# Random diye ayrı bir kütüphane olmasının yanı sıra NumPy kütüphanesinin içinde random adında bir modül de bulunur.
# NumPy'ın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [ ]:
# from numpy import random as rd
import numpy as np

In [ ]:
np.random.rand() # 0-1 arası 1 tane sayı döndürür

0.1628953331751195

In [ ]:
np.random.randn(5) # Normal dağılımdan random 5 tane veri çek. ortalaması 0 ve standart sapması 1

array([-0.21115473, -1.59997003,  0.25605988, -0.31015366, -1.8502935 ])

In [ ]:
np.random.randint(low = 10 , high = 30 , size = 5)

array([19, 12, 24, 19, 10])

In [ ]:
np.random.randint(10 , 30 , 5)

array([11, 26, 19, 15, 11])

In [ ]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [ ]:
np.random.choice(arr)

2

In [ ]:
np.random.choice([3,-1,15])

-1